name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: go test -race -timeout 3m -cover -v ./...

    - name: Go vet
      run: go vet $(go list ./...)

    - name: Golint
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2022.1.1"
        install-go: false
